language: c

env:
  global:

jobs:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - valgrind
            - check
      env:
        - GCC_MEMCHECK=true
    - os: linux
      dist: bionic
      compiler: clang
      addons:
        apt:
          packages:
            - cmake
            - valgrind
            - check
      env:
       - CLANG_RELEASE=true
#    - os: linux
#      dist: bionic
#      compiler: clang
#      addons:
#        apt:
#          packages:
#            - cmake
#            - valgrind
#            - check
#      env:
#       - INTEGRATION_TEST=true

before_install:
- pyenv versions
- pyenv global 3.8

install:
- pip install conan
- conan user
- conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
- conan remote add openRepo https://api.bintray.com/conan/matkonnerth/cpprepo

script:
  - cd ~/build/matkonnerth/nodesetLoader
  - sh ./travis_script.sh

after_success:
- echo == Build success ==

after_failure:
- echo == Build failed ==