language: c
sudo: required

env:
  global:



matrix:
  fast_finish: true
  include:

    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - valgrind
      env:
        - GCC_MEMCHECK=true

before_install:

install:

script:
  - sh ./travis_script.sh

  after_success:
  - echo == Build success ==

after_failure:
  - echo == Build failed ==