language: c

env:
  global:

jobs:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - valgrind
            - check
      env:
        - GCC_MEMCHECK=true
    - os: linux
      dist: bionic
      compiler: clang
      addons:
        apt:
          packages:
            - cmake
            - valgrind
            - check
      env:
       - CLANG_RELEASE=true

before_install:

install:
  - echo ${PWD}
  - git clone https://github.com/open62541/open62541.git
  - cd open62541
  - git submodule init && git submodule update
  - mkdir build && cd build
  - cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUA_NAMESPACE_ZERO=FULL ..
  - make -j
  - sudo make install

script:
  - cd ~/build/matkonnerth/nodesetLoader
  - sh ./travis_script.sh

after_success:
- echo == Build success ==

after_failure:
- echo == Build failed ==