language: c

env:
  global:

jobs:
  fast_finish: true
  include:
    os: linux
    dist: bionic
    compiler: gcc
    addons:
      apt:
        packages:
          - cmake
          - valgrind
          - check
    env:
      - GCC_MEMCHECK=true

before_install:

install:

script:
  sh ./travis_script.sh

after_success:
- echo == Build success ==

after_failure:
- echo == Build failed ==