language: c
sudo: required

env:
  global:



matrix:
  fast_finish: true
  include:
#
# gcc-4.8 (trusty) full host and cross build with tests:
# doc, cert, cross-mingw32, cross-mingw64, cross-linux32, cross-raspi, linux64,
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            # tests
            - check
            - valgrind
      env:
        - DEBIAN=true



before_install:

install:

script:

  - mkdir -p build
  - cd build
  - cmake .. 
  - make
  - ./parserDemo ../nodesets/testNodeset.xml
  - ./parserDemo ../nodesets/UA-Nodeset/Schema/Opc.Ua.NodeSet2.xml
  - ./parserDemo ../nodesets/UA-Nodeset/DI/Opc.Ua.Di.NodeSet2.xml
  - valgrind --error-exitcode=100 --leak-check=full ./parserDemo ../nodesets/testNodeset100nodes.xml
  
after_success:
  - echo == Build success ==

after_failure:
  - echo == Build failed ==