language: c
sudo: required

env:
  global:



matrix:
  fast_finish: true
  include:

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - check
            - valgrind
      env:
        - DEBIAN=true



before_install:

install:

jobs:
  include:
    - stage: "Build"
      script:
        - mkdir -p build
        - cd build
        - cmake .. 
        - make
        - ./parserDemo ../nodesets/testNodeset.xml
        - ./parserDemo ../nodesets/UA-Nodeset/Schema/Opc.Ua.NodeSet2.xml
        - ./parserDemo ../nodesets/UA-Nodeset/DI/Opc.Ua.Di.NodeSet2.xml
  
after_success:
  - echo == Build success ==

after_failure:
  - echo == Build failed ==